dist: trusty

language: python

python:
    - "2.7"

notifications:
    email:
        - daniel.j.dufour@gmail.com

before_install:
    - sudo apt-get install gnome-screenshot notify-osd recordmydesktop python-opencv tesseract-ocr xdotool
    - git clone https://github.com/DanielJDufour/beryl
    - pip install -e beryl/

script:
    - npm run test-gui
    
sudo:
    - required
