dist: trusty

language: python

python:
    - "2.7"

notifications:
    email:
        - daniel.j.dufour@gmail.com

before_install:
  - echo $PWD
  - ls -alsh
  - sudo apt-get -qq update
  - sudo apt-get -y install gnome-screenshot recordmydesktop python-opencv tesseract-ocr xdotool
  - sudo apt-get -y install autoconf automake build-essential cmake libass-dev libavcodec-dev libavformat-dev libfreetype6-dev libgtk2.0-dev libmp3lame-dev libswscale-dev libtheora-dev libtool libva-dev libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev nasm pkg-config texinfo yasm wget zlib1g-dev
  - sudo apt-get -y install   
  - mkdir ~/ffmpeg_sources
  - cd ~/ffmpeg_sources
  - wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
  - tar jxf ffmpeg-snapshot.tar.bz2
  - cd ffmpeg
  - PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --pkg-config-flags="--static" --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/bin" --enable-libmp3lame
  - PATH="$HOME/bin:$PATH" make -s -j
  - make install
  - hash -r
  - cd $TRAVIS_BUILD_DIR
  - cd ~/
  - git clone https://github.com/opencv/opencv.git
  - cd ~/opencv
  - mkdir release
  - cd release
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make
  - sudo make install
  - cd /home/travis/build/DanielJDufour/geotiff.io

script:
    - npm run test-gui
    
sudo:
    - required
