dist: trusty

language: python

python:
    - "2.7"

notifications:
    email:
        - daniel.j.dufour@gmail.com

before_install:
    - sudo apt-get install fluxbox gnome-screenshot libnotify-bin notify-osd recordmydesktop python-opencv tesseract-ocr wmctrl xdotool
    - sudo apt-get install libxss1 libappindicator1 libindicator7
    - echo 'installing reqs for tesseract'
    - sudo apt-get install autoconf autoconf-archive automake g++ libjpeg8-dev libpng12-dev libtiff5-dev libtool pkg-config zlib1g-dev
    - echo 'installing reqs for tesseract training'
    - sudo apt-get install libicu-dev libpango1.0-dev libcairo2-dev
    - echo 'building libleptonica required by Tesseract'
    - git clone https://github.com/DanBloomberg/leptonica
    - cd leptonica
    - mkdir build
    - cd build
    - cmake .. -DBUILD_PROG=1
    - make
    - sudo make install
    - cd ..
    - cd ..
    - echo 'installing tesseract'
    - git clone https://github.com/tesseract-ocr/tesseract/
    - cd tesseract
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - cd ..
    - echo 'installing reqs for Goolge Chrome'
    - sudo apt-get install fonts-liberation gconf2-common gconf-service gconf-service-backend libgconf-2-4 xdg-utils 
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb
    - echo 'installing chromedriver'
    - git clone https://github.com/DanielJDufour/beryl
    - pip install -e beryl/

script:
    - npm run test-gui
    
sudo:
    - required
